---
development:
  cloud_name: hjbuvseg1
  api_key: '894297247941758'
  api_secret: 3e4h-CY0g3VPJgXAnkoodmqZbt0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hjbuvseg1
  api_key: '894297247941758'
  api_secret: 3e4h-CY0g3VPJgXAnkoodmqZbt0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hjbuvseg1
  api_key: '894297247941758'
  api_secret: 3e4h-CY0g3VPJgXAnkoodmqZbt0
  enhance_image_tag: true
  static_image_support: false
